---
title: "Client Report - What's in a Name?"
subtitle: "Course DS 250"
author: "Quade Hafen"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)

df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")

```

```{python}


```
## Project Notes:



__For Project 1 the answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **two** of your charts must include reference marks.__  

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_type your results and analysis here_

```{python}
# Include and execute your code here
quade_df = df[df['name'] == 'Quade']
quade_df = quade_df.groupby('year')['Total'].sum().reset_index()

quade_df
# My name appears zero times in the data. :/
```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_type your results and analysis here_

```{python}
# Include and execute your code here
brittany_df = df[df['name'] == 'Brittany']
brittany_df = brittany_df.groupby('year')['Total'].sum().reset_index()
brittany_df = brittany_df[brittany_df['Total'] == brittany_df['Total'].max()]
brittany_df 
# Her age would be 35
```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

_type your results and analysis here_

```{python}
# Include and execute your code here
names = ["Mary", "Martha", "Peter", "Paul"]



filter_df = df[(df['name'].isin(names)) & (df['year'] >= 1920) & (df['year' ]<= 2000)]

df_grouped = filter_df.groupby(['year', 'name'], as_index=False)['Total'].sum()

# Plot
ggplot(df_grouped, aes(x='year', y='Total', color='name')) + \
    geom_line(size=1.2) + \
    ggtitle('Christian Name Usage (1920–2000)') + \
    xlab('Year') + ylab('Count of Names') + \
    theme_minimal()
    # The uses of these names all peak between 1940-1960 and they have all been trending down since.
```



## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

_type your results and analysis here_

```{python}
# Include and execute your code here
# Scarlett (Gone with the Wind) - December 15, 1939

Scarlett_df = df[df['name'] == 'Scarlett']
Scarlett_df = Scarlett_df.groupby('year')['Total'].sum().reset_index()

Scarlett_df

ggplot(Scarlett_df, aes(x='year', y='Total',)) + \
    geom_line(size=1.2) + \
    ggtitle('Usage of  Scarlett (Gone with the Wind) - December 15, 1939') + \
    xlab('Year') + ylab('Count of Names') + \
    theme_minimal()
# No, this name has only recently become popular. There is about 60 years since this movies release without much use.

```

---

## STRETCH QUESTION|TASK 1

__Reproduce the chart Elliot using the data from the `names_year.csv` file.__ 

_type your results and analysis here_

```{python}
# Include and execute your code here


```


---
